// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using john_moreau_C6_FAQs_app.Models;

#nullable disable

namespace john_moreau_C6_FAQs_app.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20231102045005_categories_and_topics")]
    partial class categories_and_topics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("john_moreau_C6_FAQs_app.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "gen",
                            Name = "General"
                        },
                        new
                        {
                            Id = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("john_moreau_C6_FAQs_app.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            CategoryId = "gen",
                            Question = "What is Bootstrap?",
                            TopicId = "bs"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            CategoryId = "gen",
                            Question = "What is C#?",
                            TopicId = "cs"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            CategoryId = "gen",
                            Question = "What is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "In 2011.",
                            CategoryId = "hist",
                            Question = "When was Bootstrap first released?",
                            TopicId = "bs"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "In 2002.",
                            CategoryId = "hist",
                            Question = "When was C# first released?",
                            TopicId = "cs"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "In 1995.",
                            CategoryId = "hist",
                            Question = "When was JavaScript first released?",
                            TopicId = "js"
                        });
                });

            modelBuilder.Entity("john_moreau_C6_FAQs_app.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "bs",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = "cs",
                            Name = "C#"
                        },
                        new
                        {
                            Id = "js",
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("john_moreau_C6_FAQs_app.Models.FAQ", b =>
                {
                    b.HasOne("john_moreau_C6_FAQs_app.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("john_moreau_C6_FAQs_app.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
