// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using john_moreau_C6_FAQs_app.Models;

#nullable disable

namespace john_moreau_C6_FAQs_app.Migrations
{
    [DbContext(typeof(FAQContext))]
    partial class FAQContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("john_moreau_C6_FAQs_app.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            Category = "General",
                            Question = "What is Bootstrap?",
                            Topic = "Bootstrap"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            Category = "General",
                            Question = "What is C#?",
                            Topic = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            Category = "General",
                            Question = "What is JavaScript?",
                            Topic = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "In 2011.",
                            Category = "History",
                            Question = "When was Bootstrap first released?",
                            Topic = "Bootstrap"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "In 2002.",
                            Category = "History",
                            Question = "When was C# first released?",
                            Topic = "C#"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "In 1995.",
                            Category = "History",
                            Question = "When was JavaScript first released?",
                            Topic = "JavaScript"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
